### ISSUE TITLE
Failed with FQDN verification of domain name including numbers other than 9

### ISSUE THREAD

**Issue by kumeichi** [gkaimakas/SwiftValidators#12]
The title is as follows.

Success: www9.example.com
Failed : www1.exaple.com

I think there is a problem with the following code.

**Validators.swift(L320)**
`if (!self.regex("[a-z\u{00a1}-\u{ffff0}-9-]+")(_part)){`

Thank you.

**Comment by gkaimakas** [comment]
I have pushed a new version `5.1.2` that addresses the issue.

Thanks for pointing it out
