### ISSUE TITLE
Email validator fails to validate valid email

### ISSUE THREAD

**Issue by mruvim** [gkaimakas/SwiftValidators#14]
Current regex to validate email is not sufficient, it will fail to validate valid emails such as 

```
name@domain.apartments
name@domain.accountants
name@domain.associates
...
```

Regex should include domains which have 6+ character extensions

**Comment by gkaimakas** [comment]
Hello @mruvim,

Thanks for noticing. It should be fixed in 6.0.1 c295a4b8a4af20d00ab1aa23bcfd67502ab8d53c
