### ISSUE TITLE
var to let

### ISSUE THREAD

**Issue by hlaporthein** [gkaimakas/SwiftValidators#24]
https://github.com/gkaimakas/SwiftValidators/blob/9d37d41e11c8655e08f894218e7fa4103e4823f6/SwiftValidators/Classes/Validator.swift#L459

**Comment by gkaimakas** [comment]
Hey @hlaporthein,

Thanks for noticing this! Would you be interested in creating a PR to fix this warning?

**Comment by hlaporthein** [comment]
@gkaimakas , OK.... it is a small case. I would make PR with a branch.
