### ISSUE TITLE
PostalCode.IT.rawValue returns wrong value

### ISSUE THREAD

**Issue by Neirys** [gkaimakas/SwiftValidators#27]
```
case DE, EE, ES, FI, IT, KE, LT, MX, SA, UA = "\\d{5}"

(lldb) po PostalCode.IT.rawValue
"IT"
(lldb) po PostalCode.UA.rawValue
"\\d{5}"
```

**Comment by gkaimakas** [comment]
Hello @Neirys ,

Thanks for opening this issue. Can you be more specific on what is the expected result and what you are getting?

**Comment by Neirys** [comment]
Hello @gkaimakas,
PostalCode regex won't work correctly because `PostalCode.IT.rawValue` returns `IT` whereas it should returns `"\\d{5}"`

**Comment by gkaimakas** [comment]
Thank you @Neirys.

9.0.3 should fix this. It should be available on SPM and CocoaPods soon
