### ISSUE TITLE
Validation error ordering issue

### ISSUE THREAD

**Issue by ronak-selldo** [gkaimakas/SwiftValidators#32]
I want to show validation error messages at time of user tap on Registration button.
Now the issue is

func validationFailed(_ errors:[(Validatable ,ValidationError)])

here errors parameter returns the fields in unordered set.

can we show error messages in ordered set?

**Comment by gkaimakas** [comment]
hey @ronak-selldo 

can you share a demo code so I better understand your use case?

**Comment by ronak-selldo** [comment]
@gkaimakas 
Please check attached code.

`class ViewController: UIViewController {

    @IBOutlet weak var nameTextField: UITextField!
    @IBOutlet weak var email: UITextField!

    let validator = Validator()

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        validator.registerField(nameTextField, rules: [RequiredRule(message: "name is required")]) // index 1
        validator.registerField(nameTextField, rules: [RequiredRule(message: "email is required")]) // index 2
    }

    @IBAction func registrationButtonTapped(_ sender: UIButton) {
        validator.validate(self)
    }
}

extension ViewController: ValidationDelegate {
    func validationSuccessful() { }

    func validationFailed(_ errors:[(Validatable ,ValidationError)]) {
        for (_, error) in errors {
            print(error.message)
            // some times it prints (I want always error messages array in ordered set.)
            // 1. name is required // actual index 1
            // 2. email is required // actual index 2

            // and some times it prints (Unordered set)
            // 1. email is required // actual index 2
            // 2. name is required // actual index 3
        }
    }
}

`

**Comment by gkaimakas** [comment]
@ronak-selldo not sure I recognise the syntax that you are using. 

The `Validator` class in this library has only one function `apply(_:) -> Bool`. There are neither `rules` nor a `ValidationDelegate`. 

Maybe you mistook this for something else? Please check your Podfile / Package.swift to make sure

**Comment by ronak-selldo** [comment]
@gkaimakas 
Sorry my bad. It is not the one which I used.

**Comment by gkaimakas** [comment]
no worries! honest mistake! take care!
