### ISSUE TITLE
Latest Update Errors

### ISSUE THREAD

**Issue by NemOry** [gkaimakas/SwiftValidators#4]
Since updating to latest version.. I get the error **"Type 'Validator' (aka 'Optional<StringConvertible> -> Bool') has no member 'isEmail'"**

MY CODE

```
import UIKit
import SwiftValidators

class TestVC: UIViewController
{
    override func viewDidLoad()
    {
        super.viewDidLoad();
        
        let is_email = Validator.isEmail("nemoryoliver@gmail.com");
        
        print("is_email: \(is_email)");
    }
}

```

**Comment by gkaimakas** [comment]
Sorry, I forgot to update the array on the docs. The `Validator` class is no more.

Use `Validators` instead

**Comment by NemOry** [comment]
Hi bro.. Even changing the Validator to Validators gives another error. **"Missing argument label 'nilResponse:' in call"**

```
import UIKit
import SwiftValidators

class TestVC: UIViewController
{
    override func viewDidLoad()
    {
        super.viewDidLoad();
        
        let x = Validators.isEmail("nemoryoliver@gmail.com");
        
        print(x);
    }
}
```

See screenshot: http://imgur.com/a/H9If9

**Comment by gkaimakas** [comment]
From version 4.0.0 there are no computed properties in the API. The `Validators` class now supports only static functions.

I have updated the documentation (16de371d69909c9cda4b7502aba4251ae4345fd9) to reflect those changes and pushed a minor version update `4.0.1` on Cocoapods.

The correct syntax to your case is the following

````
Validators.isEmail()("nemoryoliver@gmail.com")
````

Some other examples:

````
Validators.isEmail()(nil) // returns false
Validators.isEmail(nilResponse: true)(nil) // returns true
````

**Comment by NemOry** [comment]
Awesome sir. Now I know how to use your new version. Thanks a lot for this great lib. It helps a lot!
