### ISSUE TITLE
[78a6a26] Swift 3 support

### ISSUE THREAD

**Issue by meandkareem** [gkaimakas/SwiftValidators#7]

**Comment by gkaimakas** [comment]
It's on its way

**Comment by gkaimakas** [comment]
Swift 3 support was added as a new branch (Swift-3.0 78a6a26).

To use that version of `SwiftValidators` with your project add the following at your podfile

````
pod 'SwiftValidators', :git => 'https://github.com/gkaimakas/SwiftValidators', :branch => 'Swift-3.0'
````

I will push a new version on CocoaPods when `Quick` and `Nimble` migrate to Swift 3.0
